# Templated lists of boards or device families for use in the example specific section below
template:
  # Compatibility needs to be explicitly declared in all sample apps.

  # All supported boards
  board_whitelist: &board_whitelist
    - brd4111a             # efr32bg27
    - brd4117a             # efr32mg26
    - brd4181a             # efr32mg21
    - brd4182a             # efr32mg22
    - brd4186c             # efr32mg24
    - brd4194a             # efr32mg27
    - brd4204d             # efr32zg23
    - brd4270b             # efr32fg25
    - brd4400c             # efr32zg28

# Example-specific settings
example:
## Template 
#    # GPIO examples
#  - path: series2/gpio/switch_led_interrupt/SimplicityStudio/switch_led_interrupt.slcp # Path to the SLCP file
#    board_whitelist: *board_whitelist        # Reference the supported boards
#    board_blacklist:                         # Define boards that should NOT be used for this example
#      - brd4111a                             # Exclude a specific board
  
  # ACMP examples
- path: series2/acmp/acmp_vmon/SimplicityStudio/acmp_vmon.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4182a # Removing xG22 Radio Board due to lack of ACMP peripheral

- path: series2/acmp/acmp_polled/SimplicityStudio/acmp_polled.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4182a # Removing xG22 Radio Board due to lack of ACMP peripheral

- path: series2/acmp/acmp_pin_output/SimplicityStudio/acmp_pin_output.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4182a # Removing xG22 Radio Board due to lack of ACMP peripheral

- path: series2/acmp/acmp_interrupt/SimplicityStudio/acmp_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4182a # Removing xG22 Radio Board due to lack of ACMP peripheral

  # BURTC examples
- path: series2/burtc/burtc_em4_buram/SimplicityStudio/burtc_em4_buram.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

  # GPCRC examples
- path: series2/gpcrc/gpcrc_dma/SimplicityStudio/gpcrc_dma.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/gpcrc/gpcrc_software/SimplicityStudio/gpcrc_software.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

  # GPIO examples
- path: series2/gpio/switch_led_interrupt/SimplicityStudio/switch_led_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/gpio/switch_led_polled/SimplicityStudio/switch_led_polled.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/gpio/gpio_slew_rate/SimplicityStudio/gpio_slew_rate.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/gpio/gpio_periph/SimplicityStudio/gpio_periph.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/gpio/gpio_em4_wakeup/SimplicityStudio/gpio_em4_wakeup.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

  # LETIMER examples
- path: series2/letimer/one_shot_output_compare/SimplicityStudio/one_shot_output_compare.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/letimer/pulse_train/SimplicityStudio/pulse_train.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/letimer/pulse_width_modulation/SimplicityStudio/pulse_width_modulation.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

  # MSC examples
- path: series2/msc/msc_page_lock/SimplicityStudio/msc_page_lock.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/msc/msc_rw/SimplicityStudio/msc_rw.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

  # USART examples
- path: series2/usart/async_interrupt/SimplicityStudio/usart_async_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/async_polled/SimplicityStudio/usart_async_polled.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_main_dma/SimplicityStudio/usart_spi_main_dma.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_main_interrupt/SimplicityStudio/usart_spi_main_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_main_polled/SimplicityStudio/usart_spi_main_polled.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_secondary_dma/SimplicityStudio/usart_spi_secondary_dma.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_secondary_interrupt/SimplicityStudio/usart_spi_secondary_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

- path: series2/usart/spi_secondary_polled/SimplicityStudio/usart_spi_secondary_polled.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
    - brd4270b # Removing xG25 Radio Board due to lack of USART peripheral

  # WDOG examples
- path: series2/wdog/wdog_prs_clear/SimplicityStudio/wdog_prs_clear.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/wdog/wdog_prs_monitor/SimplicityStudio/wdog_prs_monitor.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/wdog/wdog_timeout_interrupt/SimplicityStudio/wdog_timeout_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/wdog/wdog_timeout_reset/SimplicityStudio/wdog_timeout_reset.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/wdog/wdog_warning_interrupt/SimplicityStudio/wdog_warning_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board

- path: series2/wdog/wdog_window_interrupt/SimplicityStudio/wdog_window_interrupt.slcp
  board_whitelist: *board_whitelist
  board_blacklist:
    - brd4111a # Removing xG27 Boost Radio Board
