# Properties file for Simplicity Studio metadata

id=uc.extension.peripheral_examples
label=peripheral_examples
description=Peripheral Examples for Simplicity SDK
version=1.0.0.0

prop.subLabel=Peripheral\\ Examples\\ Simplicity\\ SDK\\1.0.0

# General properties are prepended with "prop."
prop.file.templatesFile=peripheral_examples_evaluation_templates.xml templates.xml
prop.boardCompatibility=.*
prop.partCompatibility=.*
