// LED active low
#define LED_ON  0
#define LED_OFF 1

// <<< sl:start pin_tool >>>

// <gpio> LED0_BUTTON0
// $[GPIO_LED0_BUTTON0]
#define LED0_BUTTON0_PORT SL_GPIO_PORT_B
#define LED0_BUTTON0_PIN  0
// [GPIO_LED0_BUTTON0]$

// <gpio> LED1_BUTTON1
// $[GPIO_LED1_BUTTON1]
#define LED1_BUTTON1_PORT SL_GPIO_PORT_B
#define LED1_BUTTON1_PIN  1
// [GPIO_LED1_BUTTON1]$

// <gpio> EXP_UART_TX
// $[GPIO_EXP_UART_TX]
#define EXP_UART_TX_PORT SL_GPIO_PORT_A
#define EXP_UART_TX_PIN  5
// [GPIO_EXP_UART_TX]$

// <gpio> EXP_UART_RX
// $[GPIO_EXP_UART_RX]
#define EXP_UART_RX_PORT SL_GPIO_PORT_A
#define EXP_UART_RX_PIN  6
// [GPIO_EXP_UART_RX]$

// <gpio> WDOG_PRS
// $[GPIO_WDOG_PRS]
#define WDOG_PRS_PORT SL_GPIO_PORT_A
#define WDOG_PRS_PIN  5
// [GPIO_WDOG_PRS]$

// <gpio> EXP_SPI_COPI
// $[GPIO_EXP_SPI_COPI]
#define EXP_SPI_COPI_PORT SL_GPIO_PORT_C
#define EXP_SPI_COPI_PIN  0
// [GPIO_EXP_SPI_COPI]$

// <gpio> EXP_SPI_CIPO
// $[GPIO_EXP_SPI_CIPO]
#define EXP_SPI_CIPO_PORT SL_GPIO_PORT_C
#define EXP_SPI_CIPO_PIN  1
// [GPIO_EXP_SPI_CIPO]$

// <gpio> EXP_SPI_SCK
// $[GPIO_EXP_SPI_SCK]
#define EXP_SPI_SCK_PORT SL_GPIO_PORT_C
#define EXP_SPI_SCK_PIN  2
// [GPIO_EXP_SPI_SCK]$

// <gpio> EXP_SPI_CS
// $[GPIO_EXP_SPI_CS]
#define EXP_SPI_CS_PORT SL_GPIO_PORT_C
#define EXP_SPI_CS_PIN  3
// [GPIO_EXP_SPI_CS]$

// <gpio> SPI_TIME
// $[GPIO_SPI_TIME]
#define SPI_TIME_PORT SL_GPIO_PORT_D
#define SPI_TIME_PIN  2
// [GPIO_EXP_SPI_CS]$

// <<< sl:end pin_tool >>>
